pid /run/nginx/nginx.pid;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr info;
    sendfile on;

    server {
        listen 8080;
        server_name _;
        root /var/www/html;
        index index.html index.htm;

        location = /healthz {
            access_log off;
            return 200 "OK\n";
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
