nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}

replicaCount: 1
workload:
  type: deployment
updateStrategy:
  type: RollingUpdate

image:
  registry: ghcr.io
  repository: tpesla/python
  tag: 3.11-bookworm
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

podLabels: {}
podAnnotations: {}
podSecurityContext:
  enabled: true
  fsGroup: 0
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  enabled: true
  runAsUser: 10001
  runAsGroup: 0
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

command:
  - /bin/sh
  - -ec
args:
  - sleep infinity
env: {}
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
extraEnvFrom: []

containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP
service:
  enabled: false
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  annotations: {}

config:
  enabled: false
  filename: app.conf
  mountPath: /app/app.conf
  data: {}

persistence:
  enabled: false
  existingClaim: ""
  storageClass: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  mountPath: /app

emptyDirs: []
extraVolumes: []
extraVolumeMounts: []
initContainers: []
sidecars: []
resources: {}
lifecycle: {}

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

pdb:
  create: false
  minAvailable: ""
  maxUnavailable: 1

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: python.local
      paths:
        - path: /
          pathType: Prefix
          servicePort: http
  tls: []

openshift:
  enabled: false

metrics:
  enabled: false

networkPolicy:
  enabled: false
  allowExternal: true
  ingress: []
  egress: []

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
priorityClassName: ""
